# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommend.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'recommend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frecommend.proto\x12\nai_service\"\x1c\n\tCVRequest\x12\x0f\n\x07\x63v_text\x18\x01 \x01(\t\"\\\n\x07JobItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ompany\x18\x03 \x01(\t\x12\x0f\n\x07job_url\x18\x04 \x01(\t\x12\x14\n\x0cmatch_reason\x18\x05 \x01(\t\";\n\nCVResponse\x12-\n\x10recommended_jobs\x18\x01 \x03(\x0b\x32\x13.ai_service.JobItem2M\n\rCVRecommender\x12<\n\tAnalyzeCV\x12\x15.ai_service.CVRequest\x1a\x16.ai_service.CVResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CVREQUEST']._serialized_start=31
  _globals['_CVREQUEST']._serialized_end=59
  _globals['_JOBITEM']._serialized_start=61
  _globals['_JOBITEM']._serialized_end=153
  _globals['_CVRESPONSE']._serialized_start=155
  _globals['_CVRESPONSE']._serialized_end=214
  _globals['_CVRECOMMENDER']._serialized_start=216
  _globals['_CVRECOMMENDER']._serialized_end=293
# @@protoc_insertion_point(module_scope)
