[project]
name = "crawl-topcv-jobs"
version = "0.1.0"
description = "AI Voice Interview & Job Portal Platform"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "bs4>=0.0.2",
    "ipykernel>=6.29.5",
    "lxml>=6.0.1",
    "matplotlib>=3.7.5",
    "openpyxl>=3.1.5",
    "python-dotenv>=1.0.1",
    "pandas>=2.0.3",
    "requests>=2.32.4",
    "seaborn>=0.13.2",
    "selenium>=4.27.1",
    "webdriver-manager>=4.0.2",
    "grpcio>=1.60.0",
    "grpcio-tools>=1.60.0",
    "google-genai>=1.0.0",
    "psycopg2-binary>=2.9.9",
    "sqlalchemy>=2.0.0",
]

[project.scripts]
grpc-server = "python_grpc_server:serve"
