# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import recommend_pb2 as recommend__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in recommend_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeCV = channel.unary_unary(
                '/ai_service.AIService/AnalyzeCV',
                request_serializer=recommend__pb2.CVRequest.SerializeToString,
                response_deserializer=recommend__pb2.CVResponse.FromString,
                _registered_method=True)
        self.StartInterview = channel.unary_unary(
                '/ai_service.AIService/StartInterview',
                request_serializer=recommend__pb2.InterviewRequest.SerializeToString,
                response_deserializer=recommend__pb2.InterviewResponse.FromString,
                _registered_method=True)
        self.ChatInterview = channel.unary_unary(
                '/ai_service.AIService/ChatInterview',
                request_serializer=recommend__pb2.ChatRequest.SerializeToString,
                response_deserializer=recommend__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.EndInterview = channel.unary_unary(
                '/ai_service.AIService/EndInterview',
                request_serializer=recommend__pb2.EndRequest.SerializeToString,
                response_deserializer=recommend__pb2.EvaluationResponse.FromString,
                _registered_method=True)


class AIServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AnalyzeCV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartInterview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatInterview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndInterview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeCV': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeCV,
                    request_deserializer=recommend__pb2.CVRequest.FromString,
                    response_serializer=recommend__pb2.CVResponse.SerializeToString,
            ),
            'StartInterview': grpc.unary_unary_rpc_method_handler(
                    servicer.StartInterview,
                    request_deserializer=recommend__pb2.InterviewRequest.FromString,
                    response_serializer=recommend__pb2.InterviewResponse.SerializeToString,
            ),
            'ChatInterview': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatInterview,
                    request_deserializer=recommend__pb2.ChatRequest.FromString,
                    response_serializer=recommend__pb2.ChatResponse.SerializeToString,
            ),
            'EndInterview': grpc.unary_unary_rpc_method_handler(
                    servicer.EndInterview,
                    request_deserializer=recommend__pb2.EndRequest.FromString,
                    response_serializer=recommend__pb2.EvaluationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_service.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_service.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeCV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AIService/AnalyzeCV',
            recommend__pb2.CVRequest.SerializeToString,
            recommend__pb2.CVResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartInterview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AIService/StartInterview',
            recommend__pb2.InterviewRequest.SerializeToString,
            recommend__pb2.InterviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatInterview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AIService/ChatInterview',
            recommend__pb2.ChatRequest.SerializeToString,
            recommend__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndInterview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AIService/EndInterview',
            recommend__pb2.EndRequest.SerializeToString,
            recommend__pb2.EvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
